"""initial migration 2

Revision ID: 2ea7b0a2dbe5
Revises: 08cb2c1a0af8
Create Date: 2023-06-20 16:21:53.449578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ea7b0a2dbe5"
down_revision = "08cb2c1a0af8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("add", sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("add")

    # ### end Alembic commands ###
